# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  # dm-crypt picks its AES implementation when the initrd opens cryptroot and
  # keeps it until reboot, and the default LUKS modules don't include AES-NI.
  boot.initrd.kernelModules = [ "aesni_intel" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."cryptroot" = {
    # nvme0n1p2, encrypted in place with `cryptsetup reencrypt --encrypt`. That
    # keeps the partition's PARTUUID, while the ext4 now lives inside the mapping.
    device = "/dev/disk/by-partuuid/14c05200-e15e-40cf-8189-23f35baf7a0c";
    # Let fstrim reach the SSD, at the cost of revealing which blocks are free.
    allowDiscards = true;
    # Skip dm-crypt's work queues; better latency on NVMe.
    bypassWorkqueues = true;
  };

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9F21-E531";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # Swapfile for hibernation. It sits inside cryptroot, so the hibernation image
  # is encrypted too. zram (priority 5) is still used first; this one only takes
  # the overflow. Changing `size` recreates the file elsewhere on disk, which
  # invalidates resume_offset.
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 32 * 1024; # MiB, matches RAM
    }
  ];

  # Resume from that swapfile. The offset is where the file starts on disk, in
  # 4 KiB blocks: the first physical_offset from `filefrag -v /var/lib/swapfile`.
  boot.resumeDevice = "/dev/mapper/cryptroot";
  boot.kernelParams = [ "resume_offset=308873" ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
